Загрузите датасеты digits и breast_cancer из sklearn.datasets. Выведите несколько строчек из обучающих выборок и посмотрите на признаки. С помощью sklearn.cross_validation.cross_val_score c настройками по умолчанию и вызова метода mean() у возвращаемого этой функцией numpy.ndarray, сравните качество работы наивных байесовских классификаторов на этих двух датасетах. Для сравнения предлагается использовать BernoulliNB, MultinomialNB и GaussianNB. Насколько полученные результаты согласуются с рекомендациями из лекций?

In [6]:
import sklearn.datasets
import matplotlib.pyplot as plt
import sklearn.metrics
from matplotlib.colors import ListedColormap
from sklearn import model_selection, datasets, metrics, tree, ensemble,
import numpy as np
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [23]:
digits = datasets.load_digits()
breast_cancer = datasets.load_breast_cancer()
print(digits.data)
print(digits.target[:50])

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 9 5 5 6 5 0
 9 8 9 8 4 1 7 7 3 5 1 0 0]


In [30]:
#print (breast_cancer.DESCR)
digits_X = digits.data
digits_y = digits.target
breast_X = breast_cancer.data
breast_y = breast_cancer.target


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [50]:
#BernoulliNB, MultinomialNB и GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score

ber_cl = BernoulliNB()
mul_cl = MultinomialNB()
gau_cl = GaussianNB()

d = dict(bd = model_selection.cross_val_score(ber_cl, digits_X, digits_y).mean(),
         bb = model_selection.cross_val_score(ber_cl, breast_X, breast_y).mean(),
         md = model_selection.cross_val_score(mul_cl, digits_X, digits_y).mean(),
         mb = model_selection.cross_val_score(mul_cl, breast_X, breast_y).mean(),
         gd = model_selection.cross_val_score(gau_cl, digits_X, digits_y).mean(),
         gb = model_selection.cross_val_score(gau_cl, breast_X, breast_y).mean())


/Users/Daniel/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/Users/Daniel/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/Users/Daniel/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/Users/Daniel/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to s

In [51]:
d

{'bd': 0.8258236507780582,
 'bb': 0.6274204028589994,
 'md': 0.8708771489735053,
 'mb': 0.8945790401930752,
 'gd': 0.8186003803550138,
 'gb': 0.9367492806089297}

In [58]:
#Каким получилось максимальное качество классификации на датасете breast_cancer?

with open('/Users/Daniel/Downloads/answ1.txt', 'w') as file_obj:
    file_obj.write((str(0.9367492806089297)))

In [59]:
#Каким получилось максимальное качество классификации на датасете digits?
with open('/Users/Daniel/Downloads/answ2.txt', 'w') as file_obj:
    file_obj.write((str(0.8708771489735053)))

In [63]:
# 1) На вещественных признаках лучше всего сработал наивный байесовский классификатор 
#с распределением Бернулли

# 2) На вещественных признаках лучше всего сработал наивный байесовский классификатор 
#с мультиномиальным распределением

# 3) Мультиномиальное распределение лучше показало себя на выборке с целыми неотрицательными 
#значениями признаков

# 4) На вещественных признаках лучше всего сработало нормальное распределение

with open('/Users/Daniel/Downloads/answ3.txt', 'w') as file_obj:
    file_obj.write((str("3 4")))

In [62]:
print(digits_X)
print(breast_X)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
